### ISSUE TITLE
Job never completes

### ISSUE THREAD

**Issue by prakash2033** [moutansos/benbrougher-tech#64]
Thank you for the blog post on creating a .NET Cron Job for Kubernetes

This is to report a tiny issue.

When a cron job is triggerred in Azure kubernetes, it never completes, stays as 0/1.

Not sure what am I missing. Any inputs in resolving this is highly appreciated.

Thanks again

**Comment by moutansos** [comment]
I'll look into this and try to replicate

**Comment by prakash2033** [comment]
Thank you for your response. In my research I came to know that the Kubernetes job status being **0/1** indicates that the job has **one pod** that has **successfully completed** its execution. Even if all calls within the pod succeed without errors, the job status remains **0/1** until the specified number of successful completions is reached. This behavior ensures reliability and completion tracking for the task. One can view completed pods, use `kubectl get pods`. 😊 

There is no issue with the solution provided by in the flog. Its just how kubernetes handles cron jobs.
